[package]
name = "stm32f3discovery"
version = "0.1.0"
authors = ["Krzysztof Langner <klangner@gmail.com>"]

[dependencies.f3]
default-features = false
features = [
  "default-exception-handler",
  "default-panic-fmt"
]
version = "0.3.0"

[profile.release]
lto = true
